### ISSUE TITLE
Dockerfile not using latest version?

### ISSUE THREAD

**Issue by miraep8** [linnabrown/run_dbcan#169]
Hey all!

Thank you for putting this tool together! 

Just dropping a note as I noticed that your `Dockerfile` seems to be making use of the v11 version of the db, while from the [tutorial/website](https://dbcan.readthedocs.io/en/latest/user_guide/run_from_raw_reads.html) it seems like there is a v12 available.  If you want I would be happy to open a PR updating it so it installs the latest version of the databases, but wanted to open an issue first in case this choice was intentional!  If so may I ask why?

Best,

Mirae

**Comment by linnabrown** [comment]
Hi Mirae, thank you for pointing out that. Haidong @HaidYi is responsible for updating the docker. Since he has multiple job interviews recently he does not have enough time to maintain the tool. You don't need to PR and you can update the dockerfile by yourside to update database. In addition, we already wrote dbcan_install.py for you to install the database. Thank you very much.

**Comment by miraep8** [comment]
Best of luck @HaidYi on the job interviews!

Yea the comments about updating the Dockerfile are definitely not super pressing, might just be nice to fix eventually.  Thanks for the tip about `dbcan_install.py`!  

Another small thing - but if you all do update the image on Docker Hub in the future it might be nice to tag the various versions in order to make it easier to reference/refer back to a particular version of the software used. 

Thank you all again for this great package! :)

**Comment by maxinety** [comment]
Hello! @linnabrown @miraep8 

I also downloaded the docker image and I am confused about how to download or set up the database? I have tried the following command:

>>> dbcan_build --cpus 8 --db-dir db --clean

I also cannot seem to find or access dbcan_install.py?

Thank you for your help.

**Comment by HaidYi** [comment]
> Best of luck @HaidYi on the job interviews!
> 
> Yea the comments about updating the Dockerfile are definitely not super pressing, might just be nice to fix eventually. Thanks for the tip about `dbcan_install.py`!
> 
> Another small thing - but if you all do update the image on Docker Hub in the future it might be nice to tag the various versions in order to make it easier to reference/refer back to a particular version of the software used.
> 
> Thank you all again for this great package! :)

Hello Mirae,

I am getting back from the tough job search. Thank you for your suggestions. We have transferred the workflow from docker hub to the `github's docker package`. And the docker hub's version is no longer maintained. Starting from 4.2.0, we will release the docker image via the github package (see https://github.com/linnabrown/run_dbcan/pkgs/container/run_dbcan), and all the versions will be tagged via git so that you can easier to refer or roll back to a history version. Feel free to open an issue if you find any problems.

Again, thank you for your suggestions and stay safe!
