### ISSUE TITLE
fam-substrate-mapping.tsv does not have GT family

### ISSUE THREAD

**Issue by trx296554555** [linnabrown/run_dbcan#187]
### Report

I noticed that there is no information about the GT family in either fam-substrate-mapping-08252022.tsv or fam-substrate-mapping-08012023.tsv, but the results from dbcan_sub do include information about the GT family. Could you please clarify if this is correct? Additionally, can you inform me of the reason for the omission? I have been using this file as a parsing file previously.

And thank you very much for your reply and assistance!

**Comment by Xinpeng021001** [comment]
Hi,

During our dbCAN-sub curation in 2021, we were supposed to include the GT fams but then we temporarily removed those because of the substrate quantity and difficulties of GTs. We're planning to update it annually and in the future, we'll add it. The reason you have some GT-subs is that those CAZymes are multiple domains, including other domains like CBM/GH, which could be predicted with some substrates. I hope this could answer your question and please let us know if any other questions you have. 

Best Regards,
Xinpeng
