### ISSUE TITLE
Sequence limit reached

### ISSUE THREAD

**Issue by Vojczech** [linnabrown/run_dbcan#9]
Hello,
I am using `run_dbcan.py` older version from 4/24/18. I have input as faa file containing large number of sequences. Shortly after start of the script it gives warning

```
Waiting on HMMER
# Sequence limit reached: Max 10000 sequences are allowed
# Sequence limit reached: Max 10000 sequences are allowed
```
I would like to ask
* Does it mean that the rest of the sequences does not go for annotation, HMMER searches only in the first 10000 of sequences?
* Is it possible to change it in settings? I was not able to find it.
* Does the GitHub package have the same restriction?  
Thank you.

**Comment by linnabrown** [comment]
Yes, only the first 10000 of sequences will be used by HMMER. I'm not clear whether HMMER has this settings. To solve this problem, the easiest way is to split your input file to different files and ensure them have <10000 sequences. Because this is the issue of HMMER, the Github package still has the same restriction. 

Hope this answer can help you.

**Comment by Vojczech** [comment]
Many thanks for fast response. So is restriction for all annotations (SignalP, dbCAN,...) or is it just for SignalP (in its readme I found MAX_ALLOWED_ENTRIES settings)?

**Comment by linnabrown** [comment]
Maybe only SignalP

**Comment by Vojczech** [comment]
According to test with splitted/one-batch dataset it should be restriction for SignalP. Its output file is empty when sequence limit is reached. On the other hand, dbCAN annotation gives consistent results.
