### ISSUE TITLE
Docker image does not contain recent eCAMI bug fixes

### ISSUE THREAD

**Issue by mperisin-lallemand** [linnabrown/run_dbcan#93]
Hi,
I have been using the haidyi/run_dbcan docker image and it's been working great. I did notice that the image is behind in commits compared to the github repository and the 3.0.4 package, so I had to manually make those edits that were merged in: https://github.com/linnabrown/run_dbcan/pull/91. I'm not sure if there is a new docker image to come, so just wanted to post this for your awareness.
Thanks!

**Comment by linnabrown** [comment]
Hi,
Thanks for using our tool. We have updated the code to solve #91  in v3.0.4. Docker file don't need to update since docker command always download the most recent dbcan package from pypi (It will install v3.0.4 according to this command https://github.com/linnabrown/run_dbcan/blob/e5e5a971e11e1a313816599cb0fe5b14e551c387/docker/Dockerfile#L10). So you don't need to worry about that. Thanks for catching up this.
